export function getRandomName(): string {
  const left: string[] = [
    'admiring',
    'adoring',
    'agitated',
    'amazing',
    'angry',
    'awesome',
    'backstabbing',
    'berserk',
    'big',
    'boring',
    'clever',
    'cocky',
    'compassionate',
    'condescending',
    'cranky',
    'desperate',
    'determined',
    'distracted',
    'dreamy',
    'drunk',
    'ecstatic',
    'elated',
    'elegant',
    'evil',
    'fervent',
    'focused',
    'furious',
    'gigantic',
    'gloomy',
    'goofy',
    'grave',
    'happy',
    'high',
    'hopeful',
    'hungry',
    'insane',
    'jolly',
    'jovial',
    'kickass',
    'lonely',
    'loving',
    'mad',
    'modest',
    'naughty',
    'nauseous',
    'nostalgic',
    'pedantic',
    'pensive',
    'prickly',
    'reverent',
    'romantic',
    'sad',
    'serene',
    'sharp',
    'sick',
    'silly',
    'sleepy',
    'small',
    'stoic',
    'stupefied',
    'suspicious',
    'tender',
    'thirsty',
    'tiny',
    'trusting',
  ];
  const right: string[] = [
    'albattani',
    'allen',
    'almeida',
    'archimedes',
    'ardinghelli',
    'aryabhata',
    'austin',
    'babbage',
    'banach',
    'bardeen',
    'bartik',
    'bassi',
    'bell',
    'bhabha',
    'bhaskara',
    'blackwell',
    'bohr',
    'booth',
    'borg',
    'bose',
    'boyd',
    'brahmagupta',
    'brattain',
    'brown',
    'carson',
    'chandrasekhar',
    'colden',
    'cori',
    'cray',
    'curie',
    'darwin',
    'davinci',
    'dijkstra',
    'dubinsky',
    'easley',
    'einstein',
    'elion',
    'engelbart',
    'euclid',
    'euler',
    'fermat',
    'fermi',
    'feynman',
    'franklin',
    'galileo',
    'gates',
    'goldberg',
    'goldstine',
    'goldwasser',
    'golick',
    'goodall',
    'hamilton',
    'hawking',
    'heisenberg',
    'heyrovsky',
    'hodgkin',
    'hoover',
    'hopper',
    'hugle',
    'hypatia',
    'jang',
    'jennings',
    'jepsen',
    'joliot',
    'jones',
    'kalam',
    'kare',
    'keller',
    'khorana',
    'kilby',
    'kirch',
    'knuth',
    'kowalevski',
    'lalande',
    'lamarr',
    'leakey',
    'leavitt',
    'lichterman',
    'liskov',
    'lovelace',
    'lumiere',
    'mahavira',
    'mayer',
    'mccarthy',
    'mcclintock',
    'mclean',
    'mcnulty',
    'meitner',
    'meninsky',
    'mestorf',
    'minsky',
    'mirzakhani',
    'morse',
    'murdock',
    'newton',
    'nobel',
    'noether',
    'northcutt',
    'noyce',
    'panini',
    'pare',
    'pasteur',
    'payne',
    'perlman',
    'pike',
    'poincare',
    'poitras',
    'ptolemy',
    'raman',
    'ramanujan',
    'ride',
    'ritchie',
    'roentgen',
    'rosalind',
    'saha',
    'sammet',
    'shaw',
    'shirley',
    'shockley',
    'sinoussi',
    'snyder',
    'spence',
    'stallman',
    'stonebraker',
    'swanson',
    'swartz',
    'swirles',
    'tesla',
    'thompson',
    'torvalds',
    'turing',
    'varahamihira',
    'visvesvaraya',
    'volhard',
    'wescoff',
    'williams',
    'wilson',
    'wing',
    'wozniak',
    'wright',
    'yalow',
    'yonath',
  ];
  const li = getRandomPositiveNumber(left.length);
  const ri = getRandomPositiveNumber(right.length);

  const lv = left[li];
  const rv = right[ri];

  return `${lv} ${rv}`;
}

export function getRandomColor(): string {
  const colorPosition = getRandomPositiveNumber(fullColorList.length);

  return fullColorList[colorPosition];
}

function getRandomPositiveNumber(max: number): number {
  return Math.floor(Math.random() * max);
}

export const fullColorList = [
  '#CD6155',
  '#C0392B',
  '#A93226',

  '#EC7063',
  '#E74C3C',
  '#CB4335',

  '#AF7AC5',
  '#9B59B6',
  '#884EA0',

  '#5499C7',
  '#2980B9',

  '#1F618D',

  '#5DADE2',
  '#3498DB',
  '#2E86C1',

  '#48C9B0',
  '#1ABC9C',
  '#17A589',

  '#45B39D',
  '#16A085',
  '#138D75',

  '#0E6655',

  '#52BE80',
  '#27AE60',
  '#229954',

  '#58D68D',
  '#2ECC71',
  '#28B463',

  '#F4D03F',
  '#F1C40F',
  '#D4AC0D',

  '#F5B041',
  '#F39C12',
  '#D68910',

  '#EB984E',
  '#E67E22',
  '#CA6F1E',

  '#DC7633',
  '#D35400',
  '#BA4A00',
];
