import '../styles/wl-styles.less';
import { NavigationBar } from '../components/shared/NavBar';
import { Footer } from '../components/landing';

export default function TermsPage() {
  return (
    <>
      <NavigationBar />
      <div className="content-section-dark">
        <div className="container-small">
          <div className="article w-richtext white-text">
            <h4>
              <strong>PRIVACY POLICY</strong>
            </h4>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>Effective date: 09/28/2021</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Introduction</strong>
                </strong>
              </li>
            </ul>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>Welcome to&nbsp;</span>
              <strong>Notifire</strong>
              <span>.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                Notifire&nbsp;(&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;)
                operates&nbsp;https://hack-squad.dev&nbsp;(hereinafter referred to as &ldquo;
              </span>
              <strong>Service</strong>
              <span>&rdquo;).</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                Our Privacy Policy governs your visit to&nbsp;https://hack-squad.dev, and explains how we collect,
                safeguard and disclose information that results from your use of our Service.&nbsp;
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We use your data to provide and improve Service. By using Service, you agree to the collection and use
                of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the
                terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>Our Terms and Conditions (&ldquo;</span>
              <strong>Terms</strong>
              <span>
                &rdquo;) govern all use of our Service and together with the Privacy Policy constitutes your agreement
                with us (&ldquo;
              </span>
              <strong>agreement</strong>
              <span>&rdquo;).</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Definitions</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <strong>SERVICE&nbsp;</strong>
              <span>means the&nbsp;https://hack-squad.dev website&nbsp;operated by&nbsp;Notifire.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>PERSONAL DATA</strong>
              <span>
                &nbsp;means data about a living individual who can be identified from those data (or from those and
                other information either in our possession or likely to come into our possession).
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>USAGE DATA</strong>
              <span>
                &nbsp;is data collected automatically either generated by the use of Service or from Service
                infrastructure itself (for example, the duration of a page visit).
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>COOKIES</strong>
              <span>&nbsp;are small files stored on your device (computer or mobile device).</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>DATA CONTROLLER</strong>
              <span>
                &nbsp;means a natural or legal person who (either alone or jointly or in common with other persons)
                determines the purposes for which and the manner in which any personal data are, or are to be,
                processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong>
              <span>
                &nbsp;means any natural or legal person who processes the data on behalf of the Data Controller. We may
                use the services of various Service Providers in order to process your data more effectively.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>DATA SUBJECT&nbsp;</strong>
              <span>is any living individual who is the subject of Personal Data.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>THE USER&nbsp;</strong>
              <span>
                is the individual using our Service. The User corresponds to the Data Subject, who is the subject of
                Personal Data.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Information Collection and Use</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                We collect several different types of information for various purposes to provide and improve our
                Service to you.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Types of Data Collected</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <strong>Personal Data</strong>
            </p>
            <p>
              <span>
                While using our Service, we may ask you to provide us with certain personally identifiable information
                that can be used to contact or identify you (&ldquo;
              </span>
              <strong>Personal Data</strong>
              <span>&rdquo;). Personally identifiable information may include, but is not limited to:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>Email address</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>First name and last name</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>Phone number</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>Address, State, Province, ZIP/Postal code, City</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>Cookies and Usage Data</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We may use your Personal Data to contact you with newsletters, marketing or promotional materials and
                other information that may be of interest to you. You may opt out of receiving any, or all, of these
                communications from us&nbsp;by following the unsubscribe link.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>Usage Data</strong>
            </p>
            <p>
              <span>
                We may also collect information that your browser sends whenever you visit our Service or when you
                access Service by or through a mobile device (&ldquo;
              </span>
              <strong>Usage Data</strong>
              <span>&rdquo;).</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP
                address), browser type, browser version, the pages of our Service that you visit, the time and date of
                your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                When you access Service with a mobile device, this Usage Data may include information such as the type
                of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your
                mobile operating system, the type of mobile Internet browser you use, unique device identifiers and
                other diagnostic data.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>Tracking Cookies Data</strong>
            </p>
            <p>
              <span>
                We use cookies and similar tracking technologies to track the activity on our Service and we hold
                certain information.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies
                are sent to your browser from a website and stored on your device. Other tracking technologies are also
                used such as beacons, tags and scripts to collect and track information and to improve and analyze our
                Service.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However,
                if you do not accept cookies, you may not be able to use some portions of our Service.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>Examples of Cookies we use:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <strong>Session Cookies:</strong>
                  <span>&nbsp;We use Session Cookies to operate our Service.</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <strong>Preference Cookies:</strong>
                  <span>&nbsp;We use Preference Cookies to remember your preferences and various settings.</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <strong>Security Cookies:</strong>
                  <span>&nbsp;We use Security Cookies for security purposes.</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <strong>Advertising Cookies:</strong>
                  <span>
                    &nbsp;Advertising Cookies are used to serve you with advertisements that may be relevant to you and
                    your interests.
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Use of Data</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>Notifire&nbsp;uses the collected data for various purposes:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>to provide and maintain our Service;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>to notify you about changes to our Service;&nbsp;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    to allow you to participate in interactive features of our Service when you choose to do so;&nbsp;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>to provide customer support;&nbsp;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>to gather analysis or valuable information so that we can improve our Service;&nbsp;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>to monitor the usage of our Service;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>to detect, prevent and address technical issues;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>to fulfill any other purpose for which you provide it;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    to carry out our obligations and enforce our rights arising from any contracts entered into between
                    you and us, including for billing and collection;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    to provide you with notices about your account and/or subscription, including expiration and renewal
                    notices, email-instructions, etc.;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    to provide you with news, special offers and general information about other goods, services and
                    events which we offer that are similar to those that you have already purchased or enquired about
                    unless you have opted not to receive such information;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>in any other way we may describe when you provide the information;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>for any other purpose with your consent.&nbsp;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Retention of Data</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                We will retain your Personal Data only for as long as is necessary for the purposes set out in this
                Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our
                legal obligations (for example, if we are required to retain your data to comply with applicable laws),
                resolve disputes, and enforce our legal agreements and policies.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a
                shorter period, except when this data is used to strengthen the security or to improve the functionality
                of our Service, or we are legally obligated to retain this data for longer time periods.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Transfer of Data</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                Your information, including Personal Data, may be transferred to &ndash; and maintained on &ndash;
                computers located outside of your state, province, country or other governmental jurisdiction where the
                data protection laws may differ from those of your jurisdiction.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                If you are located outside United States and choose to provide information to us, please note that we
                transfer the data, including Personal Data, to United States and process it there.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                Your consent to this Privacy Policy followed by your submission of such information represents your
                agreement to that transfer.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                Notifire&nbsp;will take all the steps reasonably necessary to ensure that your data is treated securely
                and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an
                organisation or a country unless there are adequate controls in place including the security of your
                data and other personal information.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Disclosure of Data</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>We may disclose personal information that we collect, or you provide:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <strong>Disclosure for Law Enforcement.</strong>
                </li>
              </ol>
            </ol>
            <p>
              <span>
                Under certain circumstances, we may be required to disclose your Personal Data if required to do so by
                law or in response to valid requests by public authorities.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <strong>Business Transaction.</strong>
                </li>
              </ol>
            </ol>
            <p>
              <span>
                If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be
                transferred.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <strong>Other cases. We may disclose your information also:</strong>
                </li>
              </ol>
            </ol>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <ol>
              <ol>
                <ol>
                  <li>
                    <span>to our subsidiaries and affiliates;</span>
                  </li>
                </ol>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <ol>
                  <li>
                    <span>
                      to contractors, service providers, and other third parties we use to support our business;
                    </span>
                  </li>
                </ol>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <ol>
                  <li>
                    <span>to fulfill the purpose for which you provide it;</span>
                  </li>
                </ol>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <ol>
                  <li>
                    <span>for the purpose of including your company&rsquo;s logo on our website;</span>
                  </li>
                </ol>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <ol>
                  <li>
                    <span>for any other purpose disclosed by us when you provide the information;</span>
                  </li>
                </ol>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <ol>
                  <li>
                    <span>with your consent in any other cases;</span>
                  </li>
                </ol>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <ol>
                  <li>
                    <span>
                      if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of
                      the Company, our customers, or others.
                    </span>
                  </li>
                </ol>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Security of Data</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                The security of your data is important to us but remember that no method of transmission over the
                Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable
                means to protect your Personal Data, we cannot guarantee its absolute security.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data
                protection rights, covered by GDPR. &ndash; See more at
                https://eur-lex.europa.eu/eli/reg/2016/679/oj&nbsp;
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your
                Personal Data.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                If you wish to be informed what Personal Data we hold about you and if you want it to be removed from
                our systems, please email us at support@notifire.co.&nbsp;
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>In certain circumstances, you have the following data protection rights:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>the right to access, update or to delete the information we have on you;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    the right of rectification. You have the right to have your information rectified if that
                    information is inaccurate or incomplete;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    the right to object. You have the right to object to our processing of your Personal Data;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    the right of restriction. You have the right to request that we restrict the processing of your
                    personal information;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    the right to data portability. You have the right to be provided with a copy of your Personal Data
                    in a structured, machine-readable and commonly used format;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    the right to withdraw consent.&nbsp;You also have the right to withdraw your consent at any time
                    where we rely on your consent to process your personal information;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                Please note that we may ask you to verify your identity before responding to such requests. Please note,
                we may not able to provide Service without some necessary data.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You have the right to complain to a Data Protection Authority about our collection and use of your
                Personal Data. For more information, please contact your local data protection authority in the European
                Economic Area (EEA).
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                CalOPPA is the first state law in the nation to require commercial websites and online services to post
                a privacy policy. The law&rsquo;s reach stretches well beyond California to require a person or company
                in the United States (and conceivable the world) that operates websites collecting personally
                identifiable information from California consumers to post a conspicuous privacy policy on its website
                stating exactly the information being collected and those individuals with whom it is being shared, and
                to comply with this policy. &ndash; See more at:
                https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/&nbsp;
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>According to CalOPPA we agree to the following:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>users can visit our site anonymously;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    our Privacy Policy link includes the word &ldquo;Privacy&rdquo;, and can easily be found on the page
                    specified above on the home page of our website;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>users will be notified of any privacy policy changes on our Privacy Policy Page;</span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <ol>
              <ol>
                <li>
                  <span>
                    users are able to change their personal information by emailing us at support@notifire.co.&nbsp;
                  </span>
                </li>
              </ol>
            </ol>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>Our Policy on &ldquo;Do Not Track&rdquo; Signals:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track
                browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform
                websites that you do not want to be tracked.&nbsp;
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Service Providers</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>We may employ third party companies and individuals to facilitate our Service (&ldquo;</span>
              <strong>Service Providers</strong>
              <span>
                &rdquo;), provide Service on our behalf, perform Service-related services or assist us in analysing how
                our Service is used.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                These third parties have access to your Personal Data only to perform these tasks on our behalf and are
                obligated not to disclose or use it for any other purpose.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Analytics</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>We may use third-party Service Providers to monitor and analyze the use of our Service.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>Google Analytics</strong>
            </p>
            <p>
              <span>
                Google Analytics is a web analytics service offered by Google that tracks and reports website traffic.
                Google uses the data collected to track and monitor the use of our Service. This data is shared with
                other Google services. Google may use the collected data to contextualise and personalise the ads of its
                own advertising network.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:
                https://policies.google.com/privacy?hl=en
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We also encourage you to review the Google's policy for safeguarding your data:
                https://support.google.com/analytics/answer/6004245.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>Mixpanel</strong>
            </p>
            <p>
              <span>Mixpanel is provided by Mixpanel Inc.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of
                Mixpanel service, please visit this page: https://mixpanel.com/optout/
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                For more information on what type of information Mixpanel collects, please visit the Terms of Use page
                of Mixpanel: https://mixpanel.com/terms/
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>CI/CD tools</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We may use third-party Service Providers to automate the development process of our Service.&nbsp;
              </span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <strong>GitHub</strong>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>GitHub is provided by GitHub, Inc.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                GitHub is a development platform to host and review code, manage projects, and build software.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                For more information on what data GitHub collects for what purpose and how the protection of the data is
                ensured, please visit GitHub Privacy Policy page:
              </span>
{' '}
              <a href="https://help.github.com/en/articles/github-privacy-statement">
                <span>https://help.github.com/en/articles/github-privacy-statement.</span>
              </a>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>CircleCI</strong>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>CircleCI is provided by Circle Internet Services, Inc.&nbsp;</span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                CircleCI is Continuous Integration, a development practice which is being used by software teams
                allowing them to build, test and deploy applications easier and quicker on multiple platforms.&nbsp;
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                For more information on what data Circle CI collects for what purpose and how the protection of the data
                is ensured, please visit Circle CI Privacy Policy page: https://circleci.com/privacy/.&nbsp;
              </span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Advertising</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                We may use third-party Service Providers to show advertisements to you to help support and maintain our
                Service.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>Google AdSense DoubleClick Cookie</strong>
            </p>
            <p>
              <span>
                Google, as a third party vendor, uses cookies to serve ads on our Service. Google's use of the
                DoubleClick cookie enables it and its partners to serve ads to our users based on their visit to our
                Service or other websites on the Internet.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the
                Google Ads Settings web page: http://www.google.com/ads/preferences/
              </span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Behavioral Remarketing</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                Notifire&nbsp;uses remarketing services to advertise on third party websites to you after you visited
                our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your
                past visits to our Service.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>Google Ads (AdWords)</strong>
            </p>
            <p>
              <span>Google Ads (AdWords) remarketing service is provided by Google Inc.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads
                by visiting the Google Ads Settings page: http://www.google.com/settings/ads
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                Google also recommends installing the Google Analytics Opt-out Browser Add-on &ndash;
                https://tools.google.com/dlpage/gaoptout &ndash; for your web browser. Google Analytics Opt-out Browser
                Add-on provides visitors with the ability to prevent their data from being collected and used by Google
                Analytics.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:
                https://policies.google.com/privacy?hl=en
              </span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <strong>Twitter</strong>
            </p>
            <p>
              <span>Twitter remarketing service is provided by Twitter Inc.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You can opt-out from Twitter's interest-based ads by following their instructions:
                https://support.twitter.com/articles/20170405
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy
                page: https://twitter.com/privacy
              </span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <strong>Facebook</strong>
            </p>
            <p>
              <span>Facebook remarketing service is provided by Facebook Inc.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You can learn more about interest-based advertising from Facebook by visiting this page:
                https://www.facebook.com/help/164968693837950
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                To opt-out from Facebook's interest-based ads, follow these instructions from Facebook:
                https://www.facebook.com/help/568137493302217
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the
                Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies
                through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital
                Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital
                Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device
                settings.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                For more information on the privacy practices of Facebook, please visit Facebook's Data Policy:
                https://www.facebook.com/privacy/explanation
              </span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Payments</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                We may provide paid products and/or services within Service. In that case, we use third-party services
                for payment processing (e.g. payment processors).
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We will not store or collect your payment card details. That information is provided directly to our
                third-party payment processors whose use of your personal information is governed by their Privacy
                Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security
                Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and
                Discover. PCI-DSS requirements help ensure the secure handling of payment information.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>The payment processors we work with are:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>PayPal or Braintree:</strong>
            </p>
            <p>
              <span>Their Privacy Policy can be viewed at&nbsp;https://www.paypal.com/webapps/mpp/ua/privacy-full</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>Stripe:</strong>
            </p>
            <p>
              <span>Their Privacy Policy can be viewed at: https://stripe.com/us/privacy</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <strong>2Checkout:</strong>
            </p>
            <p>
              <span>Their Privacy Policy can be viewed at: https://www.2checkout.com/legal/privacy/&nbsp;</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Links to Other Sites</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                Our Service may contain links to other sites that are not operated by us. If you click a third party
                link, you will be directed to that third party's site. We strongly advise you to review the Privacy
                Policy of every site you visit.
              </span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                We have no control over and assume no responsibility for the content, privacy policies or practices of
                any third party sites or services.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Children's Privacy</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>Our Services are not intended for use by children under the age of 13 (&ldquo;</span>
              <strong>Children</strong>
              <span>&rdquo;).&nbsp;</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                We do not knowingly collect personally identifiable information from Children under 13. If you become
                aware that a Child has provided us with Personal Data, please contact us. If we become aware that ce
                have collected Personal Data from Children without verification of parental consent, we take steps to
                remove that information from our servers.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Changes to This Privacy Policy</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
                Privacy Policy on this page.
              </span>
            </p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>
                We will let you know via email and/or a prominent notice on our Service, prior to the change becoming
                effective and update &ldquo;effective date&rdquo; at the top of this Privacy Policy.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy
                Policy are effective when they are posted on this page.
              </span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>&nbsp;</p>
            <ul>
              <li>
                <strong>
                  <strong>Contact Us</strong>
                </strong>
              </li>
            </ul>
            <p>&nbsp;</p>
            <p>
              <strong>&nbsp;</strong>
            </p>
            <p>
              <span>If you have any questions about this Privacy Policy, please contact us:</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
            <p>
              <span>By email: support@notifire.co.</span>
            </p>
            <p>
              <span>&nbsp;</span>
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
